[package]
name = "win-file-hide"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.11", features = ["derive"] }
winapi = { version = "0.3.9", features = ["winnt", "fileapi"] }

[[bin]]
name = "hide"

[[bin]]
name = "unhide"
