[package]
name = "win-file-hide"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
winapi = { workspace = true, features = ["winnt", "fileapi"] }

[[bin]]
name = "hide"

[[bin]]
name = "unhide"
